Update package.json
Running into a dependabot error in another repo when trying to update this package:
```
ReferenceError: repository is not defined
```

I think it has to do with how the `repository` value was defined here.